const API = {
    'login': 'user/login',
    'register': 'user/register',
    'sendSmsCode': 'user/sendSmsCode',
    'resetLoginPwd': 'user/resetLoginPwd',
    'modifyLoginPwd':'user/modifyLoginPwd',
    'wechatShare' : 'user/wechatShare',
    'wechatLogin':'user/wechatLogin',
    'logout':'user/logout',
    'refreshToken' : 'user/refreshToken',
    'advList': 'publish/list',
    'advDetail': 'publish/detail',
    'advStartPlay': 'publish/startPlay',
    'advEndPlay': 'publish/endPlay',
    'shareSuccess':'publish/shareSuccess',
    'newestUsedRewards' :'reward/newestUsedRewards',
    'receive' :'reward/receive',
    'score' :'comment/score',
    'correlationVideo' :'video/relatedVideos',
    'hotVideos' : 'video/hotVideos',
    'home':'mine/home',
    'rewardList':'reward/list',
    'bindMobile':'user/bindMobile',
    'bindWechat':'user/bindWechat',
    'withdraw':'account/withdraw/wechat',
    'withdrawList':'account/withdraw/list',
    'feedback':'mine/feedback',
    'checkMobile':'user/checkMobile',
    'isValidplayId' : 'publish/videoPlayRecordValid',
    'luckyRank' : 'reward/luckyRank',
    'packetRecord':'reward/record',
    'version':'config/app/version',
    'getImageToken':'config/getCodeToken',
    'getImageCode':'config/getCode',
    'sharePacket':'share/redPacket',
    'shareContent':'share/content',
    'bindMobile':'user/bindMobile',
    'checkCanBind':'user/checkCanBind',
    'V2WechatLogin' : 'user/V2WechatLogin',
    'V2BindWechat' : 'user/V2BindWechat',
    'V2BindMobile':'user/V2BindMobile',
    'inviteRecord':'invit/invitedList',
    'subscribed':'user/subscribed',
    'conversation':'feedback/conversation',
    'invite':'mine/invit',
    'myUploadList':'uservideo/myUploadList',
    'ownerVideoList':'uservideo/ownerVideoList',
    'ownerInfo':'uservideo/ownerInfo',
    'rankings':'reward/rankings',
    'banner':'publicity/indexBanner'
}

export default API
